import time
import os

def main():
    ''' Displays hello world in a fun way '''
    clear()
    print("_")
    pause(.05)
    clear()
    print("H_")
    pause(.05)
    clear()
    print("HE_")
    pause(.05)
    clear()
    print("HEL_")
    pause(.05)
    clear()
    print("HELL_")
    pause(.05)
    clear()
    print("HELLO_")
    pause(.05)
    clear()
    print("HELLO _")
    pause(.05)
    clear()
    print("HELLO W_")
    pause(.05)
    clear()
    print("HELLO WO_")
    pause(.05)
    clear()
    print("HELLO WOR_")
    pause(.05)
    clear()
    print("HELLO WORD_")
    pause(.05)
    clear()
    print("HELLO WORDL_")
    pause(.4)
    clear()
    print("HELLO WORDL")
    pause(.4)
    clear()
    print("HELLO WORDL_")
    pause(.4)
    clear()
    print("HELLO WORDL")
    pause(.4)
    clear()
    print("HELLO WORDL_")
    pause(.1)
    clear()
    print("HELLO WORD_")
    pause(.1)
    clear()
    print("HELLO WOR_")
    pause(.3)
    clear()
    print("HELLO WORL_")
    pause(.3)
    clear()
    print("HELLO WORLD_")
    pause(.4)
    clear()
    print("HELLO WORLD")
    pause(.4)
    clear()
    print("HELLO WORLD_")
    pause(.4)
    clear()
    print("HELLO WORLD")
  
def pause(seconds):
    ''' Pauses the console for a specified amount of time in seconds '''
    time.sleep(seconds)

def clear():
    ''' Clears the console '''
    os.system('clear')

if __name__ == "__main__":
    main()